version: "3.1"

services:
  mysql:
    image: petrovalexander/mysql-5.7-mb4:latest
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: on-failure
    ports:
      - "34060:3306"
  bot:
    build:
      dockerfile: docker/bot/Dockerfile
      context: .
    restart: on-failure
    environment:
      BOT_CONFIG_FILE: /app/config.ini
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - "./app:/app/app"
      - "./config.ini:/app/config.ini"
      - "./storage:/app/storage"
