"""path column

Revision ID: 37b8df501780
Revises: 03d0443a8228
Create Date: 2018-04-24 11:04:10.685952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b8df501780'
down_revision = '03d0443a8228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'path')
    # ### end Alembic commands ###
