"""camera start date fix

Revision ID: 4507ee9c80cb
Revises: 7d2977404e00
Create Date: 2018-04-30 07:54:21.206565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4507ee9c80cb'
down_revision = '7d2977404e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('chat', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('start_date', mysql.DATETIME(), nullable=True))
    op.drop_column('camera', 'start_date')
    # ### end Alembic commands ###
