"""add file_id columns

Revision ID: b3d91f6cd581
Revises: 37b8df501780
Create Date: 2018-04-25 11:43:32.976146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d91f6cd581'
down_revision = '37b8df501780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gif', sa.Column('file_id', sa.String(length=255), nullable=True))
    op.add_column('image', sa.Column('file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'file_id')
    op.drop_column('gif', 'file_id')
    # ### end Alembic commands ###
