"""remove file_if from image

Revision ID: b7695a538c96
Revises: b3d91f6cd581
Create Date: 2018-04-25 11:54:24.360796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7695a538c96'
down_revision = 'b3d91f6cd581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_id', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True))
    # ### end Alembic commands ###
