"""add_is_mjpeg_column

Revision ID: 7c023714d4ae
Revises: aa71d842f338
Create Date: 2020-05-25 06:08:31.405489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c023714d4ae'
down_revision = 'aa71d842f338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('is_mjpeg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'is_mjpeg')
    # ### end Alembic commands ###
