"""add_url_as_is_column

Revision ID: aa71d842f338
Revises: 1a071de26fbe
Create Date: 2020-05-25 04:52:05.740020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa71d842f338'
down_revision = '1a071de26fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('url_as_is', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'url_as_is')
    # ### end Alembic commands ###
