"""message id collision fix

Revision ID: aef5cec32956
Revises: aafa1c859cf7
Create Date: 2018-05-02 12:50:10.851581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef5cec32956'
down_revision = 'aafa1c859cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'telegram_message_id')
    # ### end Alembic commands ###
